Repository ME-ICA/tedana, pull requests merged in 2018-11, with the labels that each got.

#142 Documentation update for installation and environments in miniconda
  README.md
Labels: documenting

#136 [ENH] Rename modules
  .pytest_cache/v/cache/lastfailed
  docs/api.rst
  tedana/combine.py
  tedana/decay.py
  tedana/decomposition/eigendecomp.py
  tedana/io.py
  tedana/model/__init__.py
  tedana/model/fit.py
  tedana/selection/select_comps.py
  tedana/tests/test_combine.py
  tedana/tests/test_decay.py
  tedana/tests/test_io.py
  tedana/tests/test_utils.py
  tedana/utils.py
  tedana/utils/__init__.py
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: enhancement

#134 [DOC] Update documentation for interacting with other pipelines
  docs/index.rst
  docs/usage.rst
Labels: documenting

#151 [DOC] Request for Comments: Roadmap and Contributing
  .github/pull_request_template.md
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/contributing.rst
  docs/index.rst
  docs/roadmap.rst
  docs/usage.rst
Labels: community, documenting

#44 [ENH] update ICA to sklearn from mdp
  README.md
  docs/installation.rst
  requirements.txt
  tedana/decomposition/eigendecomp.py
  tedana/info.py
  tedana/workflows/tedana.py
Labels: enhancement

#119 [ENH] Switch to Selcomps 2.5
  .circleci/config.yml
  .circleci/tedana_outputs.txt
  circle.yml
  tedana/decomposition/eigendecomp.py
  tedana/model/fit.py
  tedana/selection/__init__.py
  tedana/selection/_utils.py
  tedana/selection/select_comps.py
  tedana/workflows/tedana.py
Labels: enhancement

#158 [FIX] Loop through volumes in FIT method
  tedana/decay.py
Labels: bug
