Repository ME-ICA/tedana, pull requests merged in 2020-03, with the labels that each got.

#525 [ENH] Output and load T2* maps in seconds
  docs/api.rst
  docs/outputs.rst
  tedana/metrics/__init__.py
  tedana/tests/test_integration.py
  tedana/tests/test_utils.py
  tedana/utils.py
  tedana/viz.py
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: enhancement

#549 [FIX,TST] Adds unit tests for ma_pca functions and fixes a bug in ma_pca
  tedana/decomposition/ma_pca.py
  tedana/tests/test_mapca.py
Labels: bug, testing

#551 [DOC] Updates the TEDPCA section following changes in tedana v0.0.8
  docs/approach.rst
Labels: documentation
