Repository ME-ICA/tedana, pull requests merged in 2021-07, with the labels that each got.

#746 [FIX] Update apt in CircleCI
  .circleci/config.yml
Labels: maintenance, priority: high, testing

#696 [ENH] Add carpet plot to outputs
  docs/_static/carpet_overview.png
  docs/api.rst
  docs/outputs.rst
  tedana/io.py
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/data/html/report_carpet_buttons_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/tests/data/cornell_three_echo_outputs.txt
  tedana/tests/data/fiu_four_echo_outputs.txt
  tedana/tests/data/nih_five_echo_outputs_verbose.txt
  tedana/tests/test_io.py
  tedana/workflows/tedana.py
Labels: effort: medium, enhancement, impact: medium, priority: low, reports

#759 [ENH] Coerce images to 32-bit
  tedana/io.py
Labels: bug
