Repository ME-ICA/tedana, pull requests merged in 2024-04, with the labels that each got.

#1057 Add `--masktype` option to control adaptive mask method
  .readthedocs.yml
  docs/notebooks/plot_approach_figures.ipynb
  tedana/tests/test_decay.py
  tedana/tests/test_integration.py
  tedana/tests/test_metrics.py
  tedana/tests/test_utils.py
  tedana/utils.py
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: enhancement

#1060 Limit current adaptive mask method to brain mask
  tedana/tests/test_decay.py
  tedana/tests/test_metrics.py
  tedana/tests/test_utils.py
  tedana/utils.py
  tedana/workflows/t2smap.py
Labels: bug, breaking change

#1073 Add adaptive mask plot to report
  docs/_static/adaptive_mask.png
  docs/outputs.rst
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/tests/data/cornell_three_echo_outputs.txt
  tedana/tests/data/fiu_four_echo_outputs.txt
  tedana/tests/data/nih_five_echo_outputs_verbose.txt
  tedana/workflows/tedana.py
Labels: enhancement, reports

#1080 [DOC] desc-optcomDenoised -> desc-denoised
  docs/approach.rst
  docs/outputs.rst
Labels: documentation

#1061 Identify the last good echo in adaptive mask instead of sum of good echoes
  tedana/tests/test_utils.py
  tedana/utils.py
Labels: bug

#1044 Output RMSE map and time series for decay model fit
  docs/_static/rmse_plots.png
  docs/outputs.rst
  pyproject.toml
  tedana/decay.py
  tedana/gscontrol.py
  tedana/io.py
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/resources/config/outputs.json
  tedana/tests/data/cornell_three_echo_outputs.txt
  tedana/tests/data/fiu_four_echo_outputs.txt
  tedana/tests/data/nih_five_echo_outputs_t2smap.txt
  tedana/tests/data/nih_five_echo_outputs_verbose.txt
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: enhancement
