Repository ME-ICA/tedana, pull requests merged in 2024-02, with the labels that each got.

#1020 Reformat with new version of black
  docs/conf.py
  docs/sphinxext/github_link.py
  tedana/bibtex.py
  tedana/combine.py
  tedana/decay.py
  tedana/decomposition/ica.py
  tedana/decomposition/pca.py
  tedana/docs.py
  tedana/gscontrol.py
  tedana/io.py
  tedana/metrics/_utils.py
  tedana/metrics/collect.py
  tedana/metrics/dependence.py
  tedana/reporting/dynamic_figures.py
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/selection/component_selector.py
  tedana/selection/selection_nodes.py
  tedana/selection/selection_utils.py
  tedana/selection/tedica.py
  tedana/selection/tedpca.py
  tedana/stats.py
  tedana/tests/test_component_selector.py
  tedana/tests/test_metrics.py
  tedana/tests/test_reporting.py
  tedana/tests/test_selection_nodes.py
  tedana/tests/test_selection_utils.py
  tedana/tests/test_stats.py
  tedana/tests/test_workflows_parser_utils.py
  tedana/utils.py
  tedana/workflows/ica_reclassify.py
  tedana/workflows/parser_utils.py
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: refactoring

#1024 Add Dependabot config and switch Release Drafter to Changelog config
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/release.yml
Labels: maintenance

#1029 Pin maximum versions of dependencies in pyproject.toml
  pyproject.toml
Labels: maintenance, ignore-for-release

#1043 Document decision tree steps in report and remove log_extra_report
  docs/building_decision_trees.rst
  tedana/docs.py
  tedana/resources/decision_trees/kundu.json
  tedana/resources/decision_trees/minimal.json
  tedana/resources/references.bib
  tedana/selection/component_selector.py
  tedana/selection/selection_nodes.py
  tedana/selection/tedica.py
  tedana/tests/test_component_selector.py
  tedana/tests/test_integration.py
  tedana/tests/test_selection_nodes.py
  tedana/tests/test_selection_utils.py
  tedana/tests/test_t2smap.py
  tedana/tests/test_utils.py
  tedana/workflows/tedana.py
Labels: refactoring

#1040 Add T2* and S0 figures
  docs/_static/t2star_plots.png
  docs/outputs.rst
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/tests/data/cornell_three_echo_outputs.txt
  tedana/tests/data/fiu_four_echo_outputs.txt
  tedana/tests/data/nih_five_echo_outputs_verbose.txt
  tedana/workflows/tedana.py
Labels: enhancement, reports

#1045 Improve component plots
  tedana/reporting/static_figures.py
Labels: enhancement, reports
