Repository ME-ICA/tedana, pull requests merged in 2025-05, with the labels that each got.

#1218 More info logged for robustICA
  tedana/decomposition/ica.py
  tedana/workflows/tedana.py
Labels: enhancement, decomposition

#1221 Add gscontrol figures
  docs/_static/gsr_plots.png
  docs/outputs.rst
  tedana/gscontrol.py
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/tests/data/fiu_four_echo_outputs.txt
  tedana/workflows/tedana.py
Labels: enhancement, reports

#1232 Add `--dummy-scans` parameter to CLIs
  tedana/io.py
  tedana/metrics/external.py
  tedana/tests/test_external_metrics.py
  tedana/tests/test_io.py
  tedana/tests/test_metrics.py
  tedana/workflows/ica_reclassify.py
  tedana/workflows/t2smap.py
  tedana/workflows/tedana.py
Labels: enhancement
