Repository ME-ICA/tedana, pull requests merged in 2025-04, with the labels that each got.

#1203 add warning for when tedana calculates mask
  tedana/tests/test_integration.py
  tedana/workflows/tedana.py
Labels: documentation, effort: low

#1200 Adding classification tags options to `ica_reclassify`
  tedana/selection/component_selector.py
  tedana/selection/selection_utils.py
  tedana/tests/test_component_selector.py
  tedana/tests/test_integration.py
  tedana/tests/test_selection_utils.py
  tedana/tests/test_workflows_parser_utils.py
  tedana/workflows/ica_reclassify.py
  tedana/workflows/parser_utils.py
Labels: enhancement

#1209 Use Jinja2 to populate reports and deal with empty spaces when figures aren't added
  tedana/reporting/data/html/report_body_template.html
  tedana/reporting/data/html/report_carpet_buttons_template.html
  tedana/reporting/data/html/report_head_template.html
  tedana/reporting/data/html/report_info_table_template.html
  tedana/reporting/html_report.py
  tedana/reporting/static_figures.py
  tedana/tests/test_integration.py
Labels: bug

#1212 Properly flip ICA mixing matrix time series
  tedana/decomposition/pca.py
  tedana/metrics/collect.py
  tedana/reporting/static_figures.py
  tedana/tests/data/nih_five_echo_outputs_verbose.txt
  tedana/tests/test_metrics.py
  tedana/workflows/tedana.py
Labels: decomposition, breaking change

#1213 Don't rerun ICA if robustICA was used and clean up integration tests
  tedana/tests/data/cornell_three_echo_verbose_outputs.txt
  tedana/tests/data/reject_all_tree.json
  tedana/tests/test_external_metrics.py
  tedana/tests/test_integration.py
  tedana/tests/test_workflows_parser_utils.py
  tedana/workflows/tedana.py
Labels: testing, decomposition
